### ISSUE TITLE
Key items pocket broken after gaining old rod

### ISSUE THREAD

**Issue by BreakPoints** [vulcandth/CrystalShireEngine#11]
Again, apologies for the wobbly camera footage, I don't have a save further in on my PC.

After gaining the old rod the key items pocket list breaks. I shouldn't have a bike yet and trying to assign an item to the select key doesn't work.

https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/b73826b0-0eb2-4060-95d9-f91172688ba4

**Comment by vulcandth** [comment]
Thanks I'll look into this as soon as possible!

**Comment by vulcandth** [comment]
@BreakPoints Although this is technically fixed... your save is going to still be borked.... you'll have to manually modify the save.

I set up a public discord for CystalShireEngine. If you want some help with that find me there. https://discord.gg/4usGgu9f
