### ISSUE TITLE
Pokemon learning all it's moves in one level

### ISSUE THREAD

**Issue by BreakPoints** [vulcandth/CrystalShireEngine#16]
This Zubaz when hitting level 9 tries to learn every one of it's non-unlocked moves that it would learn through leveling.

![pokecrystal - CrystalShireEngine-0](https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/a582efc9-e90a-48c8-8016-8680e1f0409b)

https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/73b9c1aa-f0b8-40b6-99b7-95c090b9b8fc

Captured on mGBA

**Comment by vulcandth** [comment]
Oof. Thanks! I'll get that fixed asap.

**Comment by vulcandth** [comment]
Maybe I didn't fix this...

**Comment by vulcandth** [comment]
Nevermind again.. It was fixed. lol.
