### ISSUE TITLE
Incorrect Palette Reload

### ISSUE THREAD

**Issue by FrenchOrange** [vulcandth/CrystalShireEngine#18]
Object palettes won't reload properly under some circumstances, resulting in all palette entries fading to pure white. Documented cases include bringing up a Pokémon portrait in Elm's Lab, and using Flash in a dark cave.

This bug is consistent, and was discovered on the main branch with the mGBA and bgb emulators.

![image](https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/64930003/669d514c-d541-438b-8395-0c5092d70609) ![image](https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/64930003/bd3fcff6-d789-4d96-9b1e-18ab7c244c09)

**Comment by vulcandth** [comment]
Thanks i'll take a look shortly!
