### ISSUE TITLE
Gastly in intro movie

### ISSUE THREAD

**Issue by dreams897** [vulcandth/CrystalShireEngine#22]
I'm assuming this is not what was intended to have Gastly instead of Wooper in the intro movie but still use Wooper's cry? I noticed this is under a DEBUG section, but it builds it into the normal ROM

**Comment by vulcandth** [comment]
Yeah.. basically what happened is accidentally ported the into change to ghastly when I ported the debug stuff from a personal hack... The ghastly line are my favorite pokemon. I've been meaning to fix it, but sorta left it in as a mild semi-harmless joke until I get around to changing it back. Lol. Thanks for reminding me.
