### ISSUE TITLE
Crash to GBC screen when evolving Totodile (at the wrong level)

### ISSUE THREAD

**Issue by dreams897** [vulcandth/CrystalShireEngine#23]
I was able to play up until Totodile evolved but it happened at level 10 instead of 18 and caused the game to crash to the GBC screen. Tested on Gambatte emulator

**Comment by vulcandth** [comment]
Thanks. I'll check this out asap!

**Comment by vulcandth** [comment]
Really appreciate the report! Hope this resolves your issues. Can't believe this one went unnoticed this long.
