### ISSUE TITLE
Berry trees have wrong palette?

### ISSUE THREAD

**Issue by dreams897** [vulcandth/CrystalShireEngine#24]
Maybe this was done on purpose, but everything else seems vanilla so I have to question it. Berry trees have the wrong palette and should be completely green if you are wanting to have the vanilla look. 
![RetroArch_097](https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/119394167/9b641397-7076-4e01-ae84-16a84e2c4f94)

**Comment by vulcandth** [comment]
Yeah, kind of known and from the dynamic overworld object palette stuff. I'll see about fixing the palette back to vanilla.. but I was thinking long term turning those tree sprites into bg tiles.

**Comment by dreams897** [comment]
Sounds good, just thought I'd mention it
