### ISSUE TITLE
Stats screen at max volume

### ISSUE THREAD

**Issue by AtmaBuster** [vulcandth/CrystalShireEngine#27]
Normally in the stats screen, the volume is lowered to make it easier to hear the cry. When entering it the first time, this works fine, but after backing out and re-entering it, the volume is at normal/max.
Seems to come from a change made in `engine/pokemon/mon_menu.asm:_OpenPartyStats`. Zeroing out `wLastVolume` after the `call MaxVolume` seems to fix it

**Comment by vulcandth** [comment]
Thanks for the report! I'll address this asap.
