### ISSUE TITLE
Misc CSE bugs

### ISSUE THREAD

**Issue by vulcandth** [vulcandth/CrystalShireEngine#28]
The following is a list of misc CSE bugs reported by shasocastris.

- [x] Chuck becomes the player 
![image](https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/6394873/5e7560dc-68ea-4194-9ac3-05009b9d7b36)
- [ ] This dude is missing when on Olivine map vs Route40 
![image](https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/6394873/4a4520ae-44fb-49a8-98e0-33e141dda3f3)
- [x] Revive acts as a max revive (giving full HP instead of half)
- [x] Also, Ethers, Max Ethers, Elixers, Max Elixers don't restore PP, either in battle or from the overworld
- [x] (Mysteryberries work when held, but not from the pack)
- [x] Kenya Quest: The mail reads as all question marks

**Comment by CrystalLordQ** [comment]
<img width="503" alt="fix" src="https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/119171110/30e6212a-e868-4bae-84d1-fff3ec535a9a">
<img width="905" alt="fix2" src="https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/119171110/1c76ac56-6373-44bd-8af3-fc1ff5eaa53a">
commit?

**Comment by vulcandth** [comment]
> <img width="503" alt="fix" src="https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/119171110/30e6212a-e868-4bae-84d1-fff3ec535a9a">
> <img width="905" alt="fix2" src="https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/119171110/1c76ac56-6373-44bd-8af3-fc1ff5eaa53a">
> commit?

Thanks I'll make the change when I get home.
