### ISSUE TITLE
Random items appear in the overworld depending on where you enter

### ISSUE THREAD

**Issue by BreakPoints** [vulcandth/CrystalShireEngine#4]
When leaving Oak's lab a pokeball appreas next to the door, picking it up leads to some broken audio (on an analogue pocket this then leads to the music becoming corrupt and randomly dropping sounds and choosing different effects or pitches).

When entering New Bark Town from Route 29 a person and bush appear ontop of Mom's house.

https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/472268ed-43d2-4ee1-a9cc-79109e7f0f8c

**Comment by vulcandth** [comment]
Thanks! I'll check it out as soon as possible!

Is this from the core branch or the gen3 branch? And do you happen to know which commit you are on?

**Comment by BreakPoints** [comment]
[Latest commit](https://github.com/fellowship-of-the-roms/CrystalShireEngine/commit/e89823dd0a92a53783cfe3413103250e809ca503]) at the time of writing.

I'm on the core branch

**Comment by vulcandth** [comment]
Awesome! Thanks! I've been doing a lot more peephole optimizations the past couple days; so there is a good chance I introduced that bug from them. I'm am currently visiting family, but when I get home (tonight?) I'll work on fixing it. Ill update this when it's done :).

**Comment by vulcandth** [comment]
Should be good now; report back if it isn't fixed... or feel free to open new issues if you find more problems!
