### ISSUE TITLE
Main Character sprite missing from intro shrink animation

### ISSUE THREAD

**Issue by BreakPoints** [vulcandth/CrystalShireEngine#5]
The transition from high resolution to overworld sprite in the intro is missing the final sprite before gameplay.

CrystalShireEngine:

https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/4a16c77f-0299-40f8-af03-8ff19ad3ba57

Crystal V1.1:

https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/48ad1764-5b80-43e3-aee0-7f721cbc4dbf

**Comment by vulcandth** [comment]
Interesting; Thanks! I'll take a look.
