### ISSUE TITLE
Animated water too fast and missing fade effect

### ISSUE THREAD

**Issue by BreakPoints** [vulcandth/CrystalShireEngine#6]
Easier show than explained:

CrystalShireEngine Water:

https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/422fcdea-7f35-44c6-ad38-41e7f7ce62fb

OG Water:

https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/f980239a-bc1b-485d-a8c2-845b15b2e8ec

**Comment by vulcandth** [comment]
Thank you so much for these! This is most likely an issue from 60fps. I've been delaying fixing it.. Might as well do that now.

**Comment by BreakPoints** [comment]
> Thank you so much for these! This is most likely an issue from 60fps. I've been delaying fixing it.. Might as well do that now.

No worries. Looking for 60FPS with minimal changes to the base game is how I found myself here! So far it's looking perfect for a classic + QoL run on my analogue pocket. Even though that's not the stated goal for this repo.

**Comment by vulcandth** [comment]
> > Thank you so much for these! This is most likely an issue from 60fps. I've been delaying fixing it.. Might as well do that now.
> 
> No worries. Looking for 60FPS with minimal changes to the base game is how I found myself here! So far it's looking perfect for a classic + QoL run on my analogue pocket. Even though that's not the stated goal for this repo.

I haven't quite entered the deep testing phase... but I really appreciate stuff like this. These things can be easily missed.. and often times they are minor/easy fixes. Feel free to continue to find stuff XD.
