### ISSUE TITLE
White out screen visual issue

### ISSUE THREAD

**Issue by BreakPoints** [vulcandth/CrystalShireEngine#8]
Apologies for the photo, was playing on the pocket.

The black rectangle shown here was fading in and out:
![IMG_20231229_052908](https://github.com/fellowship-of-the-roms/CrystalShireEngine/assets/11966090/d24bbf3b-3fd9-453d-a837-1aa64ef84dba)

**Comment by vulcandth** [comment]
I was unable to reproduce this problem using BGB. Could be an issue with the Analogue pocket itself. I'd see if this occurs on other emulators/devices. Does it happen during every white out?

**Comment by BreakPoints** [comment]
Could be triggered only in a certain area, I'll try and repo on a standard emulator. Theoretically the Analogue pocket should be closer to hardware behaviour but FPGA cores aren't magic, could be a problem on that side.

**Comment by BreakPoints** [comment]
Ah, I remember now, I whited out in the overworld due to a poisoned pokemon, not a battle

**Comment by vulcandth** [comment]
Ah yeah; it happens in the overworld when whiting out from poison. Thanks I'll look into it.
